# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Ivan",
  "email": "ivan@mail.ru",
  "password": "shining",
  "avatar": "face.png",
  "type": "pro"
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "ivan@mail.ru",
  "password": "shining"
}

###
