# Пользователи

## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Ivan",
  "email": "ivan5@mail.ru",
  "password": "shining",
  "type": "pro"
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "ivan5@mail.ru",
  "password": "shining"
}

###

## Проверить токен пользователя
GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY3ZjFhMzE1YWE0YzhiN2VkM2NkMjVhMyIsImVtYWlsIjoiaXZhbjRAbWFpbC5ydSIsImlhdCI6MTc0Mzg5NDI1NywiZXhwIjoxNzQ0MDY3MDU3fQ._QT9SCJqRp1Xu-dPSCJF-w1AsRmmOF_8NL571lEHhbE

###

## Получить список избранных предложений пользоватетеля
GET http://localhost:5000/users/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY3ZjFhMzE1YWE0YzhiN2VkM2NkMjVhMyIsImVtYWlsIjoiaXZhbjRAbWFpbC5ydSIsImlhdCI6MTc0Mzg5NDI1NywiZXhwIjoxNzQ0MDY3MDU3fQ._QT9SCJqRp1Xu-dPSCJF-w1AsRmmOF_8NL571lEHhbE

###

## Добавить предложение в избранное пользоватетеля
POST http://localhost:5000/users/favorites/67f1b78745a075cef683c205 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY3ZjFhMzE1YWE0YzhiN2VkM2NkMjVhMyIsImVtYWlsIjoiaXZhbjRAbWFpbC5ydSIsImlhdCI6MTc0Mzg5NDI1NywiZXhwIjoxNzQ0MDY3MDU3fQ._QT9SCJqRp1Xu-dPSCJF-w1AsRmmOF_8NL571lEHhbE

###

## Удалить предложение из избранного пользоватетеля
DELETE http://localhost:5000/users/favorites/67dd3721d15eeb038cd8ebc4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY3ZjE0ODAxYmQ5ZTU0NmIyNjczNmFiOSIsIm5hbWUiOiJJdmFuIiwiZW1haWwiOiJpdmFuMkBtYWlsLnJ1IiwiaWF0IjoxNzQzODY1ODY1LCJleHAiOjE3NDQwMzg2NjV9.rSLrqQs7kd91YxIYb9fUiqll9D7zjJ1wP5DTbXC5FLU

###

## Загрузить аватар пользоватетеля

POST http://localhost:5000/users/67f14801bd9e546b26736ab9/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar.png"
Content-Type: image/png

< C:\WEB\avatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##

###
