# Предложения
## Получить список предложений
GET http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

###

## Добавить новое предложение
POST http://localhost:5000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY3ZjFhMzE1YWE0YzhiN2VkM2NkMjVhMyIsImVtYWlsIjoiaXZhbjRAbWFpbC5ydSIsImlhdCI6MTc0Mzg5NDI1NywiZXhwIjoxNzQ0MDY3MDU3fQ._QT9SCJqRp1Xu-dPSCJF-w1AsRmmOF_8NL571lEHhbE

{
  "title": "Домик у пруда — волшебное место",
  "description": "В квартире есть просторная гостиная с кухней, одна спальня и ванная комната с ванной.",
  "city": "Paris",
  "preview": "https://domainname.com/preview.jpg",
  "images": [
    "https://domainname.com/image-1.jpg",
    "https://domainname.com/image-2.jpg",
    "https://domainname.com/image-3.jpg",
    "https://domainname.com/image-4.jpg",
    "https://domainname.com/image-5.jpg",
    "https://domainname.com/image-6.jpg"
  ],
  "isPremium": true,
  "rating": 4,
  "accommodation": "house",
  "rooms": 2,
  "guests": 6,
  "price": 1560,
  "amenities": ["Breakfast", "Air conditioning", "Fridge"],
  "userId": "67f1a315aa4c8b7ed3cd25a3",
  "commentsCount": 0,
  "location": {
    "latitude": 48.85661,
    "longitude": 2.351499
  }
}

###

# Получить предложение по идентификатору
GET http://localhost:5000/offers/67f1b78745a075cef683c205 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY3ZjFhMzE1YWE0YzhiN2VkM2NkMjVhMyIsImVtYWlsIjoiaXZhbjRAbWFpbC5ydSIsImlhdCI6MTc0Mzg5NDI1NywiZXhwIjoxNzQ0MDY3MDU3fQ._QT9SCJqRp1Xu-dPSCJF-w1AsRmmOF_8NL571lEHhbE
###

## Удалить предложение по идентификатору

DELETE http://localhost:5000/offers/67dd3721d15eeb038cd8ebc1 HTTP/1.1

###

## Обновить предложение

PATCH http://localhost:5000/offers/67dd3721d15eeb038cd8ebc4 HTTP/1.1
Content-Type: application/json

{
  "title": "Ночной дозор 3",
  "description": "Проверка обновления",
  "price": 1100
}

###

## Список комментариев к объявлению
GET http://localhost:5000/offers/67f1b78745a075cef683c205/comments HTTP/1.1

###
